/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_decode_free(a: number): void;
export function decode_address(a: number, b: number): void;
export function decode_pos_parameters(a: number, b: number): void;
export function decode_pos_validator_metadata(a: number, b: number): void;
export function decode_pgf_parameters(a: number, b: number): void;
export function decode_gov_parameters(a: number, b: number): void;
export function decode_gov_proposal(a: number, b: number): void;
export function decode_gov_votes(a: number, b: number): void;
export function decode_gov_result(a: number, b: number): void;
export function decode_tx(a: number, b: number): void;
export function decode_tx_content_become_validator(a: number, b: number, c: number): void;
export function decode_tx_content_bond(a: number, b: number, c: number): void;
export function decode_tx_content_change_consensus_key(a: number, b: number, c: number): void;
export function decode_tx_content_change_validator_commission(a: number, b: number, c: number): void;
export function decode_tx_content_change_validator_metadata(a: number, b: number, c: number): void;
export function decode_tx_content_claim_rewards(a: number, b: number, c: number): void;
export function decode_tx_content_deactivate_validator(a: number, b: number, c: number): void;
export function decode_tx_content_init_account(a: number, b: number, c: number): void;
export function decode_tx_content_init_proposal(a: number, b: number, c: number): void;
export function decode_tx_content_reactivate_validator(a: number, b: number, c: number): void;
export function decode_tx_content_reveal_pk(a: number, b: number, c: number): void;
export function decode_tx_content_transfer(a: number, b: number, c: number): void;
export function decode_tx_content_update_account(a: number, b: number, c: number): void;
export function decode_tx_content_update_steward_commission(a: number, b: number, c: number): void;
export function decode_tx_content_vote_proposal(a: number, b: number, c: number): void;
export function decode_tx_content_withdraw(a: number, b: number, c: number): void;
export function decode_tx_content_resign_steward(a: number, b: number, c: number): void;
export function decode_tx_content_unjail_validator(a: number, b: number, c: number): void;
export function decode_tx_content_unbond(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_exn_store(a: number): void;
