[package]
name = "scrt-legacy-example"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
secret-cosmwasm-std = { git = "https://github.com/scrtlabs/SecretNetwork/", tag = "v1.3.1" }
serde = { version = "1.0.114", default-features = false, features = ["derive"] }
schemars = "0.7"

