---
kind: pipeline
type: docker
name: docs
trigger: { event: [ push ], branch: [ v2 ] }
steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: docs
  image: node:21-alpine3.18
  volumes: [ { name: docs, path: /var/www/docs.hack.bg } ]
  commands:
  - corepack enable
  - pnpm i --no-frozen-lockfile --strict-peer-dependencies
  - pnpm docs:typedoc3
  - du -sh ./docs
  - mkdir -p /var/www/docs.hack.bg
  - cp -r docs /var/www/docs.hack.bg/fadroma~
  - rm -rf /var/www/docs.hack.bg/fadroma
  - mv /var/www/docs.hack.bg/fadroma~ /var/www/docs.hack.bg/fadroma
volumes: [ { name: docs, host: { path: /var/www/docs.hack.bg  } } ]
---
kind: pipeline
type: docker
name: test
trigger: { event: [ push ], branch: [ v2 ] }
steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: test
  image: ghcr.io/hackbg/fadroma:v2
  commands:
  - pnpm i --no-frozen-lockfile --strict-peer-dependencies
  - pnpm cov all
