---
kind: pipeline
type: docker
name: docs
trigger: { event: [ push ], branch: [ v2 ] }
steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive --depth 1
  - printf $(git rev-parse --abbrev-ref HEAD) > BRANCH
  - cat BRANCH
- name: docs
  image: ghcr.io/hackbg/fadroma:v2
  volumes:
  - { name: cache, path: /data/ci-cache }
  - { name: docs, path: /var/www/docs.hack.bg }
  commands:
  - export BRANCH="$(cat BRANCH | tr '/' '_' | tr '\n' ' ')"
  - echo $BRANCH

  - mkdir -vp "/data/ci-cache/fadroma-docs-$BRANCH"
  - rm -rvf node_modules
  - ln -vs "/data/ci-cache/fadroma-docs-$BRANCH" node_modules
  - touch node_modules/.magic

  - mkdir -vp "/data/ci-cache/pnpm-store-v3"
  - rm -rvf ~/.local/share/pnpm
  - mkdir -p ~/.local/share/pnpm/store
  - ln -s "/data/ci-cache/pnpm-store-v3" ~/.local/share/pnpm/store/v3

  - corepack enable
  - pnpm i --no-frozen-lockfile --strict-peer-dependencies
  - pnpm docs:typedoc
  - du -sh ./docs
  - mkdir -p /var/www/docs.hack.bg
  - cp -r docs /var/www/docs.hack.bg/fadroma~
  - rm -rf /var/www/docs.hack.bg/fadroma
  - mv /var/www/docs.hack.bg/fadroma~ /var/www/docs.hack.bg/fadroma
  environment:
    FORCE_COLOR: 2
volumes:
- { name: cache, host: { path: /data/ci-cache } }
- { name: docs,  host: { path: /var/www/docs.hack.bg } }
---
kind: pipeline
type: docker
name: test
trigger: { event: [ push ], branch: [ v2 ] }
services:
- name: docker
  image: docker:24.0.7-alpine3.18
  environment:
    # Temporary docker daemon:
    DATA:   "/var/lib/docker"
    MIRROR: "http://127.0.0.1:5000"
  commands:
    - dockerd --dns 1.1.1.1 --rootless=true --bridge=none --iptables=false --data-root "$DATA" --registry-mirror "$MIRROR"
steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive --depth 1
  - printf $(git rev-parse --abbrev-ref HEAD) > BRANCH
  - cat BRANCH
- name: test
  image: ghcr.io/hackbg/fadroma:v2
  volumes: [ { name: cache, path: "/data/ci-cache" } ]
  environment:
    DOCKER_HOST: "tcp://docker:2375"
  commands:
  - export BRANCH="$(cat BRANCH | tr '/' '_' | tr '\n' ' ')"
  - echo $BRANCH

  - mkdir -vp "/data/ci-cache/fadroma-test-$BRANCH"
  - rm -rvf node_modules
  - ln -vs "/data/ci-cache/fadroma-test-$BRANCH" node_modules
  - touch node_modules/.magic

  - mkdir -vp "/data/ci-cache/pnpm-store-v3"
  - rm -rvf ~/.local/share/pnpm
  - mkdir -p ~/.local/share/pnpm/store
  - ln -s "/data/ci-cache/pnpm-store-v3" ~/.local/share/pnpm/store/v3

  - pnpm i --no-frozen-lockfile --strict-peer-dependencies
  - pnpm cov all
  environment:
    FORCE_COLOR: 2
volumes:
- { name: cache, host: { path: /data/ci-cache } }
