when: { event: push }
steps:
- name: branch
  image: alpine/git:latest
  commands: [ "printf $(git rev-parse --abbrev-ref HEAD) | tee BRANCH" ]
- name: build simf wasm blob (dev mode)
  image: oci.hack.bg/build-rust:main
  commands: [ "wasm-opt --version", "cd lib/platform && just simf-dev" ]
- name: typecheck
  image: oci.hack.bg/build-deno:main
  commands: [ "id -u", "ls -alh", "just check" ]
  backend_options: { docker: { user: 0 } }
