#!/bin/sh
deno doc -I --html --output=docs/deno index.ts
cp docs/deno/all_symbols.html docs/deno/index.html
echo '.namespaceItem{min-height:1.5rem !important;width:100%}' >> docs/deno/styles.css
echo '.namespaceItemContent{display: flex;flex-flow: row wrap}' >> docs/deno/styles.css
echo '.namespaceItemContent>a:first-child{min-width:10rem;margin-right:2rem}' >> docs/deno/styles.css
echo '.namespaceItemContentDoc{margin-top:0 !important;max-width:50%;}' >> docs/deno/styles.css
echo '.ddoc .section, .ddoc .namespaceSection{max-width:99%}' >> docs/deno/styles.css
echo '.ddoc .namespaceSection .namespaceItem .namespaceItemContent .namespaceItemContentSubItems { width: 100% }' >> docs/deno/styles.css
echo '.ddoc .namespaceSection .namespaceItem .docNodeKindIcon {flex-direction: row}' >> docs/deno/styles.css
echo '.ddoc .namespaceSection .namespaceItem .docNodeKindIcon>*+* {margin-top:0}' >> docs/deno/styles.css
echo '#topnav { display: none }' >> docs/deno/styles.css
echo '#default h2 { display: none }' >> docs/deno/styles.css
