packages:
  - 'agent'
  - 'create'
  - 'compile'
  - 'devnet'
  - 'cw'
  - 'cw/cosmjs-esm'
  - 'scrt'
  - 'scrt/secretjs-esm'

  - 'toolbox'
  - 'toolbox/*'
  - 'toolbox/ganesha/*'
  - '!toolbox/ganesha/vsc'
  - '!toolbox/ganesha/rollup'
  - '!toolbox/ganesha/test'

  - '!examples/project'

  - 'examples'
  - 'fixtures'
