packages:
  - 'toolbox'
  - 'toolbox/*'
  - 'toolbox/ganesha/*'
  - '!toolbox/ganesha/vsc'
  - '!toolbox/ganesha/rollup'
  - '!toolbox/ganesha/test'
  - 'fixtures'
  - 'packages/*'
  - 'packages/cosmjs-esm/protobuf.js'
