packages:
  - 'agent'
  - 'ops'
  - 'connect'
  - 'connect/*'
  - 'connect/cw/cosmjs-esm'
  - 'connect/cw/cosmjs-esm/ubik'
  - 'connect/scrt/secret.js'

  - 'ensuite'
  - 'ensuite/toolbox'
  - 'ensuite/toolbox/*'
  - 'ensuite/ganesha'
  - 'ensuite/ganesha/*'
  - '!ensuite/ganesha/vsc'
  - '!ensuite/ganesha/rollup'
  - '!ensuite/ganesha/test'

  - '!examples/project'
