packages:
  - 'toolbox'
  - 'toolbox/*'
  - 'toolbox/ganesha/*'
  - '!toolbox/ganesha/vsc'
  - '!toolbox/ganesha/rollup'
  - '!toolbox/ganesha/test'
  - 'fixtures'
  - 'agent'
  - 'create'
  - 'compile'
  - 'devnet'
  - 'cw'
  - 'cw/cosmjs-esm'
  - 'scrt'
  - 'scrt/secretjs-esm'
