packages:
  - 'agent'
  - 'create'
  - 'compile'
  - 'devnet'
  - 'connect'
  - 'connect/*'
  - 'connect/cw/cosmjs-esm'
  - 'connect/cw/cosmjs-esm/ubik'
  - 'connect/scrt/secretjs-esm'
  - 'connect/scrt/secretjs-esm/ubik'

  - 'toolbox'
  - 'toolbox/*'
  - 'toolbox/ganesha/*'
  - '!toolbox/ganesha/vsc'
  - '!toolbox/ganesha/rollup'
  - '!toolbox/ganesha/test'

  - '!examples/project'

  - 'examples'
  - 'fixtures'
