import type { Fn, FS, Pids, Project, Bytes } from './deps.ts';
import { Error, Base16, pipe, Dir, Text, Bin, Exec, resolvePath,
  fileURLToPath, Base64, chunked, Btc } from './deps.ts';

const defaultSimc = resolvePath(fileURLToPath(import.meta.url), '../simc');

export type ConText = FS & Pids & Project & { simc: string };

export function simfInit ({
  name = Error.required("program name")   as string,
  simf = Error.required("program source") as string[],
  wit  = null                             as Bytes,
} = {}) {
  return Dir(name,
    Text(`README.md`, chunked('\n\n')(`# ${name}`, `Generated by @hackbg/fadroma.`)),
    Text(`${name}.simc`, chunked('\n')(...simf)),
    wit && Bin(`${name}.wit`, wit));
}

export function simfBuild ({
  simc = defaultSimc,
  name = null,
  simf = name ? `${name}.simf` : Error.required("program name or path to .simf"),
  wit  = name ? `${name}.wit`  : Error.required("program name or path to .wit"),
}): Fn<[FS], Bytes> {
  return pipe(
    (ctx: FS) => Exec(simc, resolvePath(ctx.cwd, simf))(ctx),
    ({ stdout }) => stdout.split('\n')[1],
    Base64.decode
  )
}

export function simfRun ({
  btc = Btc().ExecCli,
  program = null,
} = {}) {
  return btc('sendrawtransaction', Base16.encode([0xAC, ...program]))
}
