import type { FS, Bytes } from './deps.ts';
import { Error, Base16, Base64, Dir, Text, Bin, Exec, Btc, Md,
  fileURLToPath, resolvePath, chunked, pipe, merge, Named } from './deps.ts';

/** Define a simple Simplicity program. */
export function Simplicity (...options: Partial<Simplicity>[]): Simplicity {
  const context = merge(Dir(), ...options);
  context.simc     ??= resolvePath(fileURLToPath(import.meta.url), '../simc');
  context.name     ??= Error.required("program name") as string;
  context.srcPath  ??= resolvePath(context.cwd, `${context.name}.simf`);
  context.source   ??= null as (string|string[]);
  context.witPath  ??= resolvePath(context.cwd, `${context.name}.wit`);
  context.witness  ??= null as Bytes;
  context.btc      ??= Btc().execCli;
  context.program  ??= null;
  return {
    ...context as Simplicity,

    init: Named(`Simf(Init ${context.name})`, Dir(context.cwd,
      Md(`README.md`, `# ${context.name}`, `Generated by @hackbg/fadroma`),
      Text(context.srcPath, chunked('\n')(context.source)),
      context.witness && Bin(context.witPath, context.witness))),

    build: Named(`Simf(Build ${context.name})`, pipe(
      Exec(context.simc, context.srcPath),
      ({ stdout }) => stdout.split('\n')[1], Base64.decode)),

    run: (program = context?.program||[]) => Named(`Simf(Run ${context.name})`,
      context.btc('sendrawtransaction', Base16.encode([0xAC, ...program]))),
  };
}

/** Simplicity options. */
export type SimplicityOptions = {
  simc:    string,
  name:    string,
  srcPath: string,
  source:  string|string[],
  witPath: string,
  witness: Bytes,
  btc:     Exec,
  program: Bytes
}

/** A simple Simplicity program. */
export type Simplicity = FS & SimplicityOptions & {
  init  ()
  build ()
  run   ()
};
