import type { Bytes } from './deps.ts';
import { Fn, Error, Named, Base16, Base64, Dir, Text, Bin, Exec, Btc, Md,
  fileURLToPath, resolvePath, chunked, Pipe, merge } from './deps.ts';
/** Define a simple Simplicity program. */
export function Simplicity <S extends Dir & {
  name:     string,
  srcPath:  string,
  source:   string|string[],
  witPath:  string,
  witness:  Bytes,
  program:  Bytes
  simcPath: string,
  btcPath:  string,
}> (...options: Partial<S>[]): S & {
  write: Fn,
  build: Fn,
  run:   Fn,
} {
  const {
    name     = Error.required("program name") as string,
    simcPath = resolvePath(fileURLToPath(import.meta.url), '../simc'),
    srcPath  = `${name}.simf`,
    source   = null as (string|string[]),
    witPath  = `${name}.wit`,
    witness  = null as Bytes,
    program  = null,
    ...rest
  } = merge({}, ...options) as S;
  const write = Named(`Simf(Init ${name})`, Dir(
    Md(`README.md`, `# ${name}`, `Generated by @hackbg/fadroma`),
    Text(srcPath, chunked('\n')(source)),
    witness && Bin(witPath, witness)));
  const build = Named(`Simf(Build ${name})`, Pipe(
    (...path: string[]) => Exec(simcPath, resolvePath(...path)),
    ({ stdout }) => Base64.decode(stdout.split('\n')[1])));
  const run = Named(`Simf(Run ${name})`,
    p => Btc().execCli('signrawtransactionwithwallet', Base16.encode(p)));
  return {
    name, srcPath, source, witPath, witness, program,
    write, build, run,
    ...rest as S
  }
}
