[package]
name    = "fadroma-proc-message"
version = "0.1.0"
edition = "2018"
license = "AGPL-3.0"
repository = "https://github.com/hackbg/fadroma"
authors = ["Adam Avramov <adam@hack.bg>"]

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
quote = "1.0"
proc-macro2 = "^1.0.20"
