test:
  deno test --coverage --allow-read=pkg 2>&1
  deno coverage
check:
  deno check index.ts
build-debug:
  wasm-pack build --dev --target web && rm -v pkg/package.json pkg/.gitignore
build-release:
  wasm-pack build --release --target web && rm -v pkg/package.json pkg/.gitignore
