#!/usr/bin/env -S deno run --allow-env
import { suite, the } from '../context/tester.ts';
export default suite(import.meta, 'Solana',
  the('Web3',
    the('Localnet', the('Connect'), the('Subscribe')),
    the('Fetch', the('Block'), the('Account'), the('TX')),
    the('Gas', the('Drop'), the('Send')),
    the('Fungible', the('Deploy'), the('Mint/burn'), the('Send'), the('Allowance'), the('Decimals')),
    the('NFT', the('Deploy'), the('Transact')),
    the('Program', the('Deploy'), the('Invoke'))),
  the('Kit',
    the('Localnet', the('Connect'), the('Subscribe')),
    the('Fetch', the('Block'), the('Account'), the('TX')),
    the('Gas', the('Drop'), the('Send')),
    the('Fungible', the('Deploy'), the('Mint/burn'), the('Send'), the('Allowance'), the('Decimals')),
    the('NFT', the('Deploy'), the('Transact')),
    the('Program', the('Deploy'), the('Invoke'))),
  the('Program',
    the('Init'), the('Build'), the('Deploy'), the('Test'),
    the('SDK', the('Test'), the('CLI'), the('GUI'))));
