[package]
name = "fadroma-example-admin"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fadroma = { path = "../../crates/fadroma", features = ["scrt", "ensemble"] }
counter = { package = "fadroma-example-derive-contract-interface", path = "../derive-contract-interface" }
serde = { version = "1.0.114", default-features = false, features = ["derive"] }
