[package]
name = "test1"
version = "0.0.0"
edition = "2021"
authors = []
keywords = ["fadroma"]
description = ""
readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fadroma = { git = "https://github.com/hackbg/fadroma", branch = "feat/podman-nix", features = ["scrt"] }
serde = { version = "1.0.114", default-features = false, features = ["derive"] }