#!/usr/bin/env -S deno run --allow-env
import Test from '../../library/Test.ts';
export default Test(import.meta, 'Solana',
  Test('Web3',
    Test('Localnet', Test('Connect'), Test('Subscribe')),
    Test('Fetch', Test('Block'), Test('Account'), Test('TX')),
    Test('Gas', Test('Drop'), Test('Send')),
    Test('Fungible', Test('Deploy'), Test('Mint/burn'), Test('Send'), Test('Allowance'), Test('Decimals')),
    Test('NFT', Test('Deploy'), Test('Transact')),
    Test('Program', Test('Deploy'), Test('Invoke'))),
  Test('Kit',
    Test('Localnet', Test('Connect'), Test('Subscribe')),
    Test('Fetch', Test('Block'), Test('Account'), Test('TX')),
    Test('Gas', Test('Drop'), Test('Send')),
    Test('Fungible', Test('Deploy'), Test('Mint/burn'), Test('Send'), Test('Allowance'), Test('Decimals')),
    Test('NFT', Test('Deploy'), Test('Transact')),
    Test('Program', Test('Deploy'), Test('Invoke'))),
  Test('Program',
    Test('Init'), Test('Build'), Test('Deploy'), Test('Test'),
    Test('SDK', Test('Test'), Test('CLI'), Test('GUI'))));
