/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_decode_free(a: number): void;
export function decode_u32(a: number, b: number): void;
export function decode_u64(a: number, b: number): void;
export function decode_vec_string(a: number, b: number): void;
export function decode_code_hash(a: number, b: number): void;
export function decode_storage_keys(a: number): void;
export function decode_epoch_duration(a: number, b: number): void;
export function decode_gas_cost_table(a: number, b: number): void;
export function decode_tx(a: number, b: number): void;
export function decode_address(a: number, b: number): void;
export function decode_addresses(a: number, b: number): void;
export function decode_address_to_amount(a: number, b: number): void;
export function decode_block(a: number, b: number, c: number, d: number, e: number): void;
export function decode_pos_parameters(a: number, b: number): void;
export function decode_pos_validator_metadata(a: number, b: number): void;
export function decode_pos_commission_pair(a: number, b: number): void;
export function decode_pos_validator_state(a: number, b: number): void;
export function decode_pos_validator_set(a: number, b: number): void;
export function decode_pgf_parameters(a: number, b: number): void;
export function decode_gov_parameters(a: number, b: number): void;
export function decode_gov_proposal(a: number, b: number): void;
export function decode_gov_votes(a: number, b: number): void;
export function decode_gov_result(a: number, b: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_exn_store(a: number): void;
