simf:
	cd simf && wasm-pack build --release --target web && rm -v pkg/package.json pkg/.gitignore
simf-dev:
	cd simf && wasm-pack build --dev --target web && rm -v pkg/package.json pkg/.gitignore

namada:
	cd namada && wasm-pack build --release --target web && rm -v pkg/package.json pkg/.gitignore
namada-dev:
	cd namada && wasm-pack build --dev --target web && rm -v pkg/package.json pkg/.gitignore
