simf:
	cd SimplicityHL && wasm-pack build --release --target web && rm -v pkg/package.json pkg/.gitignore
simf-dev:
	cd SimplicityHL && wasm-pack build --dev --target web && rm -v pkg/package.json pkg/.gitignore

namada:
	cd Namada && wasm-pack build --release --target web && rm -v pkg/package.json pkg/.gitignore
namada-dev:
	cd Namada && wasm-pack build --dev --target web && rm -v pkg/package.json pkg/.gitignore
