describe('SecretNetworkAgent', () => {
  it('can be created from a mnemonic', ()=>{})
  it('can be created from a keypair', ()=>{})
  it('can be created from a signing pen', ()=>{})
  it('can be created with an empty wallet', () => {})
  it('can have a name', () => {})
  it('can read chain state', () => {})
  it('can read its own balance', () => {})
  it('can send SCRT', () => {})
  it('can send SCRT to many addresses in one go', ()=>{})
  it('can interact with contracts', ()=>{})
  it('can deploy contracts', ()=>{})
})
