import { timestamp } from '@hackbg/konzola'
import { CommandContext } from '@hackbg/komandi'
import type { Task } from '@hackbg/komandi'
import { hide, into, intoRecord } from './core-fields'
import type { Class, Overridable, Into, IntoArray, IntoRecord } from './core-fields'
import { ClientError, ClientConsole } from './core-events'
import { assertAgent, assertAddress } from './core-connect'
import type { Address, TxHash, Agent, Chain, ChainId, Message, ContractLink, Client, ClientClass } from './core-connect'
import { ContractTemplate } from './core-upload'
import type { Builder, ContractSource } from './core-build'
import { intoSource } from './core-build'
import type { Uploader } from './core-upload'
import type { CodeHash, CodeId } from './core-code'
import { fetchCodeHash, getSourceSpecifier, assertCodeHash } from './core-code'
import type { Name, Label, StructuredLabel } from './core-labels'
import { writeLabel } from './core-labels'

export * from './core-deploy-attach'
export * from './core-deploy-contract'
export * from './core-deploy-contracts'
export * from './core-deploy-instance'
export * from './core-deploy-store'
export * from './core-deployment'
