list:
  @just --list
wasm:
  time wasm-pack build --debug --no-opt --target web
  rm -v pkg/package.json pkg/.gitignore
wasm-release:
  time wasm-pack build --release --target web
  rm -v pkg/package.json pkg/.gitignore
