[package]
name    = "fadroma-example-kv"
version = "1.0.0"
authors = []
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
path = "kv.rs"

[dependencies]
fadroma = { path = "../../crates/fadroma", features = ["scrt"] }
serde = { version = "1.0.114", default-features = false, features = ["derive"] }
