[package]
name    = "fadroma-example-kv"
version = "1.0.0"
authors = []
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
path = "kv.rs"

[dependencies]
fadroma = { git = "https://github.com/hackbg/fadroma", branch = "v100", features = ["scrt"] }
serde   = { version = "1.0.103", default-features = false, features = ["derive"] }
