[package]
name = "fadroma-example-factory-product"
version = "0.1.0"
edition = "2021"
authors = [
  "Asparuh Kamenov <aakamenov@hack.bg>",
  "Adam A. <adam@hack.bg>",
]
keywords = ["fadroma"]
description = ""
readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fadroma = { path = "../../crates/fadroma", features = [ "scrt" ] }
serde = { version = "1.0.114", default-features = false, features = ["derive"] }
fadroma-example-factory-shared = { path = "../factory-shared" }
