/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HandleAnswer =
  | {
      deposit: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      redeem: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      transfer: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      send: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      batch_transfer: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      batch_send: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      burn: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      register_receive: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      create_viewing_key: {
        key: ViewingKey;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      set_viewing_key: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      increase_allowance: {
        allowance: Uint128;
        owner: HumanAddr;
        spender: HumanAddr;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      decrease_allowance: {
        allowance: Uint128;
        owner: HumanAddr;
        spender: HumanAddr;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      transfer_from: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      send_from: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      batch_transfer_from: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      batch_send_from: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      burn_from: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      batch_burn_from: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      mint: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      batch_mint: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      add_minters: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      remove_minters: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      set_minters: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      change_admin: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      set_contract_status: {
        status: ResponseStatus;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type ResponseStatus = "success" | "failure";
export type ViewingKey = string;
export type Uint128 = string;
export type HumanAddr = string;
