name: Fadroma Build Container
on: [push, pull_request]
jobs:
  build-container:
    name: build the build container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          tags:    ghcr.io/hackbg/fadroma:${{ github.ref_name }}
          push:    true
      - run: echo ${{ steps.docker_build.outputs.digest }}
