name: Fadroma (Docker)
on: [push]

jobs:

  build-builder:
    name: build the build container image
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v2, with: { submodules: recursive } }
      - { id: buildx, name: Set up Docker Buildx, uses: docker/setup-buildx-action@v1 }
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "IMAGE_TAG=$(tr '/' '_' <<< ${{ github.ref_name }})" >> $GITHUB_ENV
      - uses: docker/build-push-action@v4
        with:
          context: .
          tags: ghcr.io/hackbg/fadroma:${{ env.IMAGE_TAG }}
          push: true
      - run: echo ${{ steps.docker_build.outputs.digest }}

  build-devnet:
    name: build the devnet container images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "IMAGE_TAG=$(tr '/' '_' <<< ${{ github.ref_name }})" >> $GITHUB_ENV
      - uses: docker/build-push-action@v4
        with:
          context: ./ops
          file:    ops/scrt_1_8.Dockerfile
          tags:    ghcr.io/hackbg/fadroma-devnet-scrt-1.8:${{ env.IMAGE_TAG }}
          push:    true
      - uses: docker/build-push-action@v4
        with:
          context: ./ops
          file:    ops/scrt_1_7.Dockerfile
          tags:    ghcr.io/hackbg/fadroma-devnet-scrt-1.7:${{ env.IMAGE_TAG }}
          push:    true
      - uses: docker/build-push-action@v4
        with:
          context: ./ops
          file:    ops/scrt_1_6.Dockerfile
          tags:    ghcr.io/hackbg/fadroma-devnet-scrt-1.6:${{ env.IMAGE_TAG }}
          push:    true
      - uses: docker/build-push-action@v4
        with:
          context: ./ops
          file:    ops/scrt_1_5.Dockerfile
          tags:    ghcr.io/hackbg/fadroma-devnet-scrt-1.5:${{ env.IMAGE_TAG }}
          push:    true
