name: Fadroma (TypeScript)
on: [push]
jobs:
  js:
    name: pnpm ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.5.2
          run_install: |
            - recursive: true
      - run: pnpm ci

