name: Fadroma (TypeScript)
on: [push]
jobs:
  js:
    name: PNPM CI
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - name: Clone with submodules
        uses: actions/checkout@v4
        with: { submodules: recursive }
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with: { version: 7.29.1 }
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          check-latest: true
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Setup Rust cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Run pnpm ci
        env:
          FORCE_COLOR: 2
        run: |
          git config --global user.email "hello@fadroma.tech"
          git config --global user.name "Hello Fadroma"
          sudo apt install -y wabt binaryen cloc
          mkdir -p wasm
          rustup default 1.69
          rustup target add wasm32-unknown-unknown --toolchain 1.69
          pnpm --version
          pnpm i --frozen-lockfile
          FADROMA_BUILD_RAW=1 TEMP="$(dirname $(pwd))" TMP="$(dirname $(pwd))" pnpm run ci

# See https://github.com/pnpm/pnpm/issues/6424 for why not Node 20
