name: Fadroma (TypeScript)
on: [push]
jobs:
  js:
    name: pnpm ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          check-latest: true
      - run: |
          corepack enable
          mkdir -p wasm
          rustup target add wasm32-unknown-unknown
          FADROMA_BUILD_RAW=1 TEMP="$(dirname $(pwd))" TMP="$(dirname $(pwd))" pnpm ci
