name: Fadroma
on: [push]

jobs:

  rs-publish:
    name: cargo publish --dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Get the source, no submodules
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile:   minimal
          toolchain: stable
          target:    wasm32-unknown-unknown
          override:  true
      - name: Unveil Cargo.toml
        run: cp _Cargo.toml Cargo.toml
      - name: Run cargo publish --dry-run
        run: |
          cargo publish --dry-run -p fadroma
          cargo publish --dry-run -p fadroma-derive-canonize
          cargo publish --dry-run -p fadroma-proc-auth
          cargo publish --dry-run -p fadroma-proc-derive
          cargo publish --dry-run -p fadroma-proc-message

  rs-coverage:
    name: cargo tarpaulin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { submodules: true }
      - uses: actions-rs/toolchain@v1
        with:
          profile:   minimal
          toolchain: stable
          target:    wasm32-unknown-unknown
          override:  true
      - uses: Swatinem/rust-cache@v1
      - name: Unveil Cargo.toml
        run: cp _Cargo.toml Cargo.toml
      - uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.18.3'
          args: '--workspace --ignore-panics --ignore-tests --exclude-files=platforms/* --coveralls ${{secrets.COVERALLS_REPO_TOKEN}} --exclude-files platforms'

  js:
    name: pnpm ts:ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.5.2
          run_install: |
            - recursive: true
      - run: pnpm ts:ci

  ci-images:
    name: build container images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          tags:    ghcr.io/hackbg/fadroma:${{ github.ref_name }}
          push:    true
      - run: echo ${{ steps.docker_build.outputs.digest }}
