name: Fadroma (Rust)
on: [push]
jobs:
  rs-publish:
    name: cargo publish --dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Get the source, no submodules
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile:   minimal
          toolchain: stable
          target:    wasm32-unknown-unknown
          override:  true
      - name: Unveil Cargo.toml
        run: cp _Cargo.toml Cargo.toml
      - name: Run cargo publish --dry-run
        run: |
          cargo publish --dry-run -p fadroma -F scrt
          cargo publish --dry-run -p fadroma-derive-canonize
          cargo publish --dry-run -p fadroma-proc-auth
          cargo publish --dry-run -p fadroma-proc-derive
          cargo publish --dry-run -p fadroma-proc-message
  #rs-coverage:
    #name: cargo tarpaulin
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2
        #with: { submodules: true }
      #- uses: actions-rs/toolchain@v1
        #with:
          #profile:   minimal
          #toolchain: stable
          #target:    wasm32-unknown-unknown
          #override:  true
      #- uses: Swatinem/rust-cache@v1
      #- name: Unveil Cargo.toml
        #run: cp _Cargo.toml Cargo.toml
      #- uses: actions-rs/tarpaulin@v0.1
        #with:
          #version: '0.18.3'
          #args: '--workspace --ignore-panics --ignore-tests --exclude-files=platforms/* --coveralls ${{secrets.COVERALLS_REPO_TOKEN}} --exclude-files platforms'
