name: Fadroma (Rust)
on: [push]
jobs:
  rs-publish:
    name: cargo publish --dry-run
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - name: Get the source, no submodules
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile:   minimal
          toolchain: stable
          target:    wasm32-unknown-unknown
          override:  true
      - name: Setup Rust cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Try building for WASM
        run: cargo build --all-features --target wasm32-unknown-unknown
  #rs-coverage:
    #name: cargo tarpaulin
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v4
        #with: { submodules: true }
      #- uses: actions-rs/toolchain@v1
        #with:
          #profile:   minimal
          #toolchain: stable
          #target:    wasm32-unknown-unknown
          #override:  true
      #- uses: Swatinem/rust-cache@v1
      #- name: Unveil Cargo.toml
        #run: cp _Cargo.toml Cargo.toml
      #- uses: actions-rs/tarpaulin@v0.1
        #with:
          #version: '0.18.3'
          #args: '--workspace --ignore-panics --ignore-tests --exclude-files=platforms/* --coveralls ${{secrets.COVERALLS_REPO_TOKEN}} --exclude-files platforms'
