export * as Scrt from './platforms/scrt-devnet'
export * as OKP4 from './platforms/okp4-devnet'
export * as Archway from './platforms/archway-devnet'
export * as Osmosis from './platforms/osmosis-devnet'
export * as Injective from './platforms/injective-devnet'
export * as Axelar from './platforms/axelar-devnet'
