export * as Scrt      from './platforms/devnet-scrt'
export * as OKP4      from './platforms/devnet-okp4'
export * as Archway   from './platforms/devnet-archway'
export * as Osmosis   from './platforms/devnet-osmosis'
export * as Injective from './platforms/devnet-injective'
export * as Axelar    from './platforms/devnet-axelar'
