[package]
name = "fadroma-example-kv"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fadroma = { path = "../..", features = ["scrt", "vk", "ensemble"] }
serde = { version = "1.0.114", default-features = false, features = ["derive"] }
