//! # Fadroma

/// Import commonly used definitions that need to be available everywhere in the contract
#[macro_export] macro_rules! prelude {
    () => { use fadroma::scrt::cosmwasm_std::{
        Storage, Api, Querier, Extern, Env,
        HumanAddr, CanonicalAddr, Coin, Uint128,
        StdResult, StdError,
        InitResponse, HandleResponse, LogAttribute, Binary,
        CosmosMsg, BankMsg, WasmMsg, to_binary,
        log
    }; };
}

// The `message!` and `messages!` macros depend on derive macros from serde and schemars.
// This complicates the reexport via fadroma core due to how procedural macros resolve crates
// (see https://github.com/serde-rs/serde/issues/1465#issuecomment-458420543)
// The workaround at https://github.com/serde-rs/serde/issues/1465#issuecomment-800686252
// is automatically implemented in the `mod msg` generated by the `contract!` macro
// This is done automatically in the `mod msg` defined by the `contract!` macro. However if
// you use the message macros manually, it is up to you to implement a corresponding workaround.

/// Define an enum that implements the necessary traits
/// (de/serialization, schema generation, cloning, debug printing, equality comparison)
#[macro_export] macro_rules! message {
    ( $Msg:ident { $( $(#[$meta:meta])* $field:ident : $type:ty ),* } ) => {
        #[derive(Clone,Debug,PartialEq,serde::Serialize,serde::Deserialize,schemars::JsonSchema)]
        #[serde(rename_all="snake_case")]
        pub struct $Msg { $( $(#[$meta])* pub $field: $type ),* } } }

/// Define an enum with variants that implement the necessary traits
#[macro_export] macro_rules! messages {
    ( $( $Enum:ident {
        $( $(#[$meta:meta])* $Msg:ident { $(
            $(#[$field_meta:meta])* 
            $field:ident : $type:ty
        ),* } )*
    } )*
    ) => { $(
        #[derive(Clone,Debug,PartialEq,serde::Serialize,serde::Deserialize,schemars::JsonSchema)]
        #[serde(rename_all="snake_case")]
        pub enum $Enum { $(
            $(#[$meta])* $Msg { $(
                $(#[$field_meta])*
                $field : $type
            ),* }
        ),* } )*
    }
}

/// Define the state singleton.
// TODO: Support other shapes of state
#[macro_export] macro_rules! define_state_singleton {
    (
        $State:ident
        { $( $(#[$meta:meta])* $state_field:ident : $state_field_type:ty ),* }
    ) => {
        /// State singleton
        message!($State { $($(#[$meta])* $state_field:$state_field_type),* });
        use fadroma::scrt::cosmwasm_storage::{Singleton, singleton, ReadonlySingleton, singleton_read};
        pub static CONFIG_KEY: &[u8] = b"fadroma_root_state";
        pub fn get_store_rw<S: Storage>(storage: &mut S) -> Singleton<S, $State> {
            singleton(storage, CONFIG_KEY)
        }
        pub fn get_store_ro<S: Storage>(storage: &S) -> ReadonlySingleton<S, $State> {
            singleton_read(storage, CONFIG_KEY)
        }
    }
}

/// Instantiation interface.
#[macro_export] macro_rules! define_init_message {
    // if imported:
    ($_:ident, $Import:ident) => { pub use super::$Import; };
    // if defined in place:
    ($Name:ident, { $(
        $(#[$meta:meta])* $arg:ident : $type:ty
    ),* }) => {
        message!($Name { $($arg: $type),* });
    }
}

/// Query interface.
#[macro_export] macro_rules! define_q_messages {
    // if imported:
    ($_1:tt, $Import:ident, { $($_2:tt)* }) => { pub use super::$Import; };
    // if defined in place:
    ($Name:ident, { $(
        $(#[$meta:meta])* $Variant:ident ( $(
            $(#[$arg_meta:meta])* $arg:ident : $type:ty
        ),* )
    )* }) => {
        messages!($Name { $( $(#[$meta])* $Variant {$(
            $(#[$arg_meta])* $arg: $type
        ),*} )* });
    };
}

/// Transaction interface.
#[macro_export] macro_rules! define_tx_messages {
    // if imported:
    ($_1:tt, $Import:ident, { $($_2:tt)* }) => { pub use super::$Import; };
    // if defined in place:
    ($Name:ident, { $(
        $(#[$meta:meta])* $Variant:ident ( $(
            $(#[$arg_meta:meta])* $arg:ident : $type:ty
        ),* )
    )* }) => {
        messages!($Name { $( $(#[$meta])* $Variant {$(
            $(#[$arg_meta])* $arg: $type
        ),*} )* });
    };
}

/// Instatiation. Either defines or imports an `InitMsg`, and hooks up your init logic to it.
/// Function body must return the initial value of `State`.
#[macro_export] macro_rules! implement_init {
    // define the InitMsg in place:
    (
        $(#[$InitMeta:meta])* [$Init:ident]
        ($deps:ident, $env:ident, $msg:ident :{ $($field:ident : $type:ty),* }) $body:block
    ) => {
        use msg::$Init;
        $(#[$InitMeta])*
        pub fn init <S: Storage, A: Api, Q: Querier>(
            $deps: &mut Extern<S, A, Q>, $env: Env, $msg: $Init
        ) -> StdResult<InitResponse> {
            $(let $field : $type = $msg.$field;)*
            macro_rules! save_state {
                // Storing the global state of the contract with this macro
                ($global_state:expr) => { get_store_rw(&mut $deps.storage).save(&$global_state)?; }
            };
            Ok($body)
        }
    };
    // or import it from an external module:
    (
        $(#[$InitMeta:meta])* [$_:ident]
        ($deps:ident, $env:ident, $msg:ident : $InitExt:ty ) $body:block
    ) => {
        $(#[$InitMeta])*
        pub fn init <S: Storage, A: Api, Q: Querier>(
            $deps: &mut Extern<S, A, Q>, $env: Env, $msg: $InitExt
        ) -> StdResult<InitResponse> {
            // no auto-destructuring because the macro is not aware of the struct fields
            macro_rules! save_state {
                // Storing the global state of the contract with this macro
                ($global_state:expr) => { get_store_rw(&mut $deps.storage).save(&$global_state)?; }
            };
            $body;
            Ok(InitResponse::default())
        }
    };
}

/// Query implementations.
#[macro_export] macro_rules! implement_queries {
    // for external query message type, ignore the name in the brackets
    // and pass through to the next macro variantb
    (
        $State:ident, $EnumExt:ident, $_:ident
        ( $deps:ident, $state:ident, $msg:ident ) -> $Response:ident { $($bodies:tt)* }
    ) => {
        implement_queries!($State, $EnumExt ( $deps, $state, $msg ) -> $Response { $($bodies)* });
    };

    // implement queries defined in $body
    (
        $State:ident, $Enum:ident
        ( $deps:ident, $state:ident, $msg:ident ) -> $Response:ident { $(
            $(#[$meta:meta])* $Variant:ident ( $($field:ident : $type:ty),*)
            $body:tt
        )* }
    ) => {
        /// Query dispatcher.
        pub fn query <S: Storage, A: Api, Q: Querier> (
            $deps: &Extern<S, A, Q>, $msg: msg::$Enum
        ) -> StdResult<Binary> {
            let state = get_store_ro(&$deps.storage).load()?; // get snapshot of contract state
            let result = match $msg { $( // find the matching handler
                msg::$Enum::$Variant {..} => self::queries::$Variant($deps, state, $msg),
            )* };
            Ok(fadroma::scrt::cosmwasm_std::to_binary(&result?)?) // return handler result
        }
        /// Query handlers.
        mod queries {
            prelude!();
            use super::{*, msg::Response};
            // for every query message variant, define a handler 
            $(
                $(#[$meta])*
                #[allow(non_snake_case)]
                pub fn $Variant <S: Storage, A: Api, Q: Querier>(
                    $deps: &Extern<S, A, Q>, $state: $State, $msg: msg::$Enum,
                ) -> StdResult<$Response> {
                    if let super::msg::$Enum::$Variant {$($field),*} = $msg { // destructure the message
                        $body // perform user-specified actions
                    } else { unreachable!() }
                }
            )*
        }

    }
}

/// Transaction implementations
#[macro_export] macro_rules! implement_transactions {
    (   $State:ident, $Enum:ident, $_:ident
        ($deps:ident, $env:ident, $state:ident, $msg:ident) -> $Response:ident { $($bodies:tt)* }
    ) => {
        implement_transactions!($State, $Enum ($deps, $env, $state, $msg) -> $Response { $($bodies)* });
    };
    (   $State:ident, $Enum:ident
        ($deps:ident, $env:ident, $state:ident, $msg:ident) -> $Response:ident {
            $($(#[$meta:meta])* $Variant:ident ( $($arg:ident $(: $type:ty)?),* ) $body:block)*
        }
    ) => {
        /// Transaction dispatcher
        pub fn handle <S: Storage, A: Api, Q: Querier> (
            $deps: &mut Extern<S, A, Q>, $env: Env, $msg: msg::$Enum,
        ) -> StdResult<HandleResponse> {
            // pick the handler that matches the message and call it:
            match $msg { $(
                msg::$Enum::$Variant {..} => self::handle::$Variant($deps, $env, $msg),
            )* }
        }
        /// Transaction handlers
        mod handle {
            prelude!();
            use super::*;
            // shorthand for saving state
            // define a handler for every tx message variant
            $(#[allow(non_snake_case)] pub fn $Variant <S: Storage, A: Api, Q: Querier>(
                $deps: &mut Extern<S, A, Q>,
                $env:  Env,
                $msg:  msg::$Enum,
            ) -> StdResult<HandleResponse> {
                // get mutable snapshot of current state:
                let mut $state = get_store_rw(&mut $deps.storage).load()?;
                macro_rules! save_state {
                    () => { get_store_rw(&mut $deps.storage).save(&$state)?; }
                };
                if let super::msg::$Enum::$Variant {$($arg),*} = $msg {
                    // perform user-specified actions
                    $body
                } else {
                    unreachable!()
                }
            })*
        }
    };
}

/// Define a smart contract
#[macro_export] macro_rules! contract {

    // This pattern matching is ugly!
    (
        // passed to `define_state_singleton!`
        [$State:ident]
        { $( $(#[$meta:meta])* $state_field:ident : $state_field_type:ty ),* }

        // Define the signature of the init message, how it's handled.
        //
        $(#[$InitMeta:meta])*
        [$Init:ident]
        ( $init_deps:ident, $init_env:ident, $init_msg:ident : $($init_msg_definition:tt)+
        ) $init_body:block

        // Define query messages and how they're handled:
        [$Q:ident]
        ( $q_deps:ident, $q_state:ident, $q_msg:ident $( : $ExtQ:ident)? )
        -> $QResponse:ident { $(
            $(#[$QVariantMeta:meta])* $QVariant:ident ($(
                $(#[$QVariantArgMeta:meta])*
                $q_arg:ident $(: $q_arg_type:ty)?
            ),*) $q_body:tt
        )* }

        // Define possible responses:
        [$Response:ident] {
        $( $(#[$response_meta:meta])* $ResponseMsg:ident { $($resp_field:ident : $resp_field_type:ty),* } )* }

        // Define transaction messages and how they're handled:
        [$TX:ident]
        ( $tx_deps:ident, $tx_env:ident, $tx_state:ident, $tx_msg:ident $( : $ExtTX:ident)? )
        -> $TXResponse:ident { $(
            $(#[$TXVariantMeta:meta])* $TXVariant:ident ($(
                $(#[$TXVariantArgMeta:meta])*
                $tx_arg:ident $(: $tx_arg_type:ty)?
            ),*) $tx_body:tt
        )* }

    ) => {

        prelude!();

        /// WASM entry points.
        // Similar in spirit to [`create_entry_points`](https://docs.rs/cosmwasm-std/0.10.1/src/cosmwasm_std/entry_points.rs.html#49),
        // but doesn't need the implementation to be in a sibling module (the `super::contract` on L65)
        // TODO custom `migrate` for SecretNetwork
        #[cfg(all(target_arch = "wasm32", not(feature = "browser")))]
        mod wasm {
            //use super::contract;
            use fadroma::scrt::cosmwasm_std::{
                ExternalStorage as Storage, ExternalApi as Api, ExternalQuerier as Querier,
                do_init, do_handle, do_query
            };
            #[no_mangle] extern "C" fn init (env_ptr: u32, msg_ptr: u32) -> u32 {
                do_init(&super::init::<Storage, Api, Querier>, env_ptr, msg_ptr)
            }
            #[no_mangle] extern "C" fn handle (env_ptr: u32, msg_ptr: u32) -> u32 {
                do_handle(&super::handle::<Storage, Api, Querier>, env_ptr, msg_ptr)
            }
            #[no_mangle] extern "C" fn query (msg_ptr: u32) -> u32 {
                do_query(&super::query::<Storage, Api, Querier>, msg_ptr,)
            }
            // Other C externs like cosmwasm_vm_version_1, allocate, deallocate are available
            // automatically because we `use cosmwasm_std`.
        }

        #[cfg(all(target_arch = "wasm32", feature = "browser"))]
        mod wasm {
            use wasm_bindgen::prelude::{wasm_bindgen, JsValue};
            use fadroma::scrt::cosmwasm_std as cw;

            // can't augment structs we don't own, so wrap 'em:
            #[wasm_bindgen] pub struct Deps(cw::Extern<cw::MemoryStorage, Api, Querier>);

            #[wasm_bindgen] pub struct Env(cw::Env);
            #[wasm_bindgen] impl Env {
                #[wasm_bindgen(constructor)] pub fn new () -> Self {
                    Self(cw::Env {
                        block: cw::BlockInfo {
                            height:   0u64,
                            time:     0u64,
                            chain_id: String::new()
                        },
                        message: cw::MessageInfo {
                            sender:     cw::HumanAddr::from(""),
                            sent_funds: vec![]
                        },
                        contract: cw::ContractInfo {
                            address: cw::HumanAddr::from("")
                        },
                        contract_key: Some(String::new()),
                        contract_code_hash: String::new()
                    })
                }
            }

            #[wasm_bindgen] pub struct Init(super::msg::$Init);
            #[wasm_bindgen] impl Init {
                #[wasm_bindgen(constructor)] pub fn new (json: &[u8]) -> Result<Init, JsValue> {
                    match cw::from_slice(json) {
                        Ok(res) => Ok(Self(res)),
                        Err(e) => Err(StdError(e).into())
                    }
                }
            }
            #[wasm_bindgen] pub struct InitResponse(cw::InitResponse);

            #[wasm_bindgen] pub struct Q(super::msg::$Q);
            #[wasm_bindgen] pub struct Binary(cw::Binary);
            #[wasm_bindgen] pub struct Response(super::msg::$Response);

            #[wasm_bindgen] pub struct TX(super::msg::$TX);
            #[wasm_bindgen] pub struct HandleResponse(cw::HandleResponse);

            #[wasm_bindgen] pub struct HumanAddr(cw::HumanAddr);
            #[wasm_bindgen] pub struct CanonicalAddr(cw::CanonicalAddr);

            #[wasm_bindgen] pub struct StdError(cw::StdError);

            #[wasm_bindgen]
            #[derive(Copy, Clone)]
            pub struct Api {}
            impl cw::Api for Api {
                fn canonical_address (&self, addr: &cw::HumanAddr) -> cw::StdResult<cw::CanonicalAddr> {
                    Ok(cw::CanonicalAddr(cw::Binary(Vec::from(addr.as_str()))))
                }
                fn human_address (&self, addr: &cw::CanonicalAddr) -> cw::StdResult<cw::HumanAddr> {
                    let trimmed: Vec<u8> = addr.as_slice().iter().cloned().filter(|&x| x != 0).collect();
                    // decode UTF-8 bytes into string
                    Ok(cw::HumanAddr(String::from_utf8(trimmed).map_err(cw::StdError::invalid_utf8)?))
                }
            }

            impl From<cw::StdError> for StdError {
                fn from (err: cw::StdError) -> Self {
                    Self(err)
                }
            }

            #[wasm_bindgen] pub struct Querier {}
            impl cw::Querier for Querier {
                fn raw_query (&self, bin_request: &[u8]) -> cw::QuerierResult {
                    Ok(cw::to_binary(&[] as &[u8]))
                }
            }

            #[wasm_bindgen] pub struct Contract {
                deps: Deps,
            }

            #[wasm_bindgen] impl Contract {

                #[wasm_bindgen(constructor)] pub fn new () -> Self {
                    Self {
                        deps: Deps(cw::Extern {
                            storage:  cw::MemoryStorage::default(),
                            api:      Api {},
                            querier:  Querier {}
                        })
                    }
                }

                pub fn init (&mut self, env: Env, msg: Init) -> Result<InitResponse, JsValue> {
                    match super::init(&mut self.deps.0, env.0, msg.0) {
                        Ok(res) => Ok(InitResponse(res)),
                        Err(e) => Err(StdError(e).into())
                    }
                }

                pub fn handle (&mut self, env: Env, msg: TX) -> Result<HandleResponse, JsValue> {
                    match super::handle(&mut self.deps.0, env.0, msg.0) {
                        Ok(res) => Ok(HandleResponse(res)),
                        Err(e) => Err(StdError(e).into())
                    }
                }

                pub fn query (&self, msg: Q) -> Result<Binary, JsValue> {
                    match super::query(&self.deps.0, msg.0) {
                        Ok(res) => Ok(Binary(res)),
                        Err(e) => Err(StdError(e).into())
                    }
                }

            }

        }

        /// This contract's on-chain API.
        pub mod msg {
            // The argument sets of the {Init,Query,Handle}Msg handlers
            // are used to automatically generate the corresponding
            // protocol messages.
            // * This is why the @Q/@TX/@Response sub-sections are not just passed in as opaque `tt`s
            // * Only responses can't be inferred and need to be pre-defined.
            // * Although, with some more macro trickery, they could be defined in place
            //   (e.g. the return types of $Q handlers could be defined as
            //   `-> Foo { field: type }` and then populated with `return Self { field: value }`
            // * Let's revisit this once some we have some more examples of custom responses
            //
            prelude!();

            use super::*;

            define_init_message!($Init, $($init_msg_definition)+);

            define_q_messages!($Q, $($ExtQ,)? {
                $( $(#[$QVariantMeta])* $QVariant ($(
                    $(#[$QVariantArgMeta])*
                    $q_arg $(: $q_arg_type)?
                ),*))*
            });

            define_tx_messages!($TX, $($ExtTX,)? {
                $( $(#[$TXVariantMeta])* $TXVariant ($(
                    $(#[$TXVariantArgMeta])*
                    $tx_arg $(: $tx_arg_type)?),*
                ))*
            });

            messages!($Response { $(
                $(#[$response_meta])* $ResponseMsg {$($resp_field: $resp_field_type),*}
            )* });
        }

        /// Implementations
        //use msg::{$Init,$Q,$TX,$Response};

        define_state_singleton! {
            $State { $( $(#[$meta])* $state_field : $state_field_type ),* }
        }

        implement_init! {
            $(#[$InitMeta])* [$Init]
            ($init_deps, $init_env, $init_msg : $($init_msg_definition)+) $init_body
        }

        implement_queries! {
            $State, $($ExtQ,)? $Q ($q_deps, $q_state, $q_msg) -> $QResponse { $(
                $(#[$QVariantMeta])* $QVariant
                ($($q_arg $(: $q_arg_type)?),*) $q_body
            )* }
        }

        implement_transactions! {
            $State, $($ExtTX,)? $TX ($tx_deps, $tx_env, $tx_state, $tx_msg) -> $TXResponse { $(
                $(#[$TXVariantMeta])* $TXVariant
                ($( $tx_arg $(: $tx_arg_type)?),*) $tx_body
            )* }
        }

    };

}

// TODO proposed action against the triple generic:
// scrt-contract automatically aliases `storage`, `api`,
// and `querier` (also maybe the contents of `env`?)
// so that it becomes less verbose to pass just the ones you use
// (...that, or let's just give contracts a `self` already?)
